# COMMENT: These are two basic redirect rules
# COMMENT: This is an abbreviated syntax for rules that fit in one line
redirects = [
  {from = "/posts/page/2", to = "/posts/"},
  {from = "/posts/page/3", to = "/posts/"},
  {from = "/posts/page/4", to = "/posts/"},
  {from = "/posts/page/5", to = "/posts/"}]
