// This file is generated by Slice Machine. Update with care!

import CodeBlock from './CodeBlock';
import Image from './Image';
import Markdown from './Markdown';
import TextBlock from './TextBlock';

export {
	CodeBlock,
	Image,
	Markdown,
	TextBlock,
};

export const components = {
	code_block: CodeBlock,
	image: Image,
	markdown: Markdown,
	text_block: TextBlock,
};
