// This file is generated by Slice Machine. Update with care!

import CategoryPosts from './CategoryPosts';
import CodeBlock from './CodeBlock';
import Image from './Image';
import Markdown from './Markdown';
import Recommendations from './Recommendations';
import TextBlock from './TextBlock';

export {
	CategoryPosts,
	CodeBlock,
	Image,
	Markdown,
	Recommendations,
	TextBlock,
};

export const components = {
	category_posts: CategoryPosts,
	code_block: CodeBlock,
	image: Image,
	markdown: Markdown,
	recommendations: Recommendations,
	text_block: TextBlock,
};
